name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # or your desired PHP version

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction

      - name: Run PHPStan (Static Analysis)
        run: |
          mkdir -p /tmp/phpstan  # Create a temporary directory if it doesn't exist
          php vendor/bin/phpstan analyse --memory-limit=512M || echo "PHPStan failed" > phpstan-results.json

      - name: Run Laravel Pint (Code Formatting)
        run: |
          php vendor/bin/pint --test || echo "Pint found issues, but continuing"

      - name: Run PHP_CodeSniffer (PSR-12 Standards)
        run: |
          if [ -f vendor/bin/phpcs ]; then
            php vendor/bin/phpcs --standard=PSR12
          else
            echo "PHP_CodeSniffer not found"
          fi

      - name: Auto-fix PHP_CodeSniffer issues
        run: |
          if [ -f vendor/bin/phpcbf ]; then
            php vendor/bin/phpcbf --standard=PSR12
          else
            echo "PHP_CodeSniffer Auto-Fix not found"
          fi

      - name: Commit code fixes (if any)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-fix code style and static analysis issues"
          git push

      - name: Upload PHPStan results as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: phpstan-results
          path: phpstan-results.json
