name: Laravel CI/CD (Self-Hosted Runner)
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:

jobs:
  build:
    runs-on: self-hosted  # Self-hosted runner use hoga
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # PHP 8.1 use hoga
          extensions: mbstring, xml, ctype, json, bcmath, curl, fileinfo, intl, gd, zip

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Run Tests
        run: php artisan test

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Use Secret Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@52.64.175.187 << 'EOF'
            sudo apt update
            sudo apt install -y php8.1 php8.1-mbstring php8.1-xml php8.1-ctype php8.1-json php8.1-bcmath php8.1-curl php8.1-fileinfo php8.1-intl php8.1-gd php8.1-zip composer git unzip
            cd /path/to/your/app
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan config:cache
            sudo systemctl restart apache2  # Apache/Nginx Restart
          EOF
